config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'petitions#petitions'

   get 'petitions/index'
   get 'petitions/new'
   get 'sessions/new'
   get 'signup', to: 'users#new', as: 'signup'
   get 'login', to: 'sessions#new', as: 'login'

  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/show_users', to: 'users#show',     via: 'get'
  match '/home_index', to: 'home#index',     via: 'get'
     resources :petitions
     resources :users
     resources :sessions
     resources :votes

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_and_belongs_to_many :petitions
end

app/models/petition.rb
class Petition < ActiveRecord::Base
  belongs_to :user
  has_many :votes
  has_and_belongs_to_many :genres
  ACTIVE_DAYS = 90
  NEED_VOTES = 100
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true
  validates :text, presence: true
  validates :user_id, presence: true

  def voted_by?(user)
    votes.where(user_id: user.id).any?
  end

  def expired?(id)
    user.petitions.find_by(id: id).created_at < ACTIVE_DAYS.days.ago
  end

  def self.search(search)
    Petition.where("title ILIKE ?", "%#{search}%")
    Petition.where("text ILIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :petitions, dependent: :destroy
  has_many :votes, dependent: :destroy
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :petition
  belongs_to :user
  validates :user_id, uniqueness: {scope: :petition_id}
  validate :active_petition, on: :create

  def active_petition
    errors.add(:petition_id, 'is not active') if :petition.expired?(petition_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include SimpleCaptcha::ControllerHelpers

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  helper_method :current_user

  def authorize
    redirect_to login_url, alert: 'Вы не авторизованы' if current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pititions = current_user.petitions.build if signed_in?
  end
  # def home
  #   if signed_in?
  #     @pitition  = current_user.petitions.build
  #     @feed_items = current_user.feed.paginate(page: params[:page])
  #   end
  # end
end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  before_filter :authorize, only: [:new, :create]
  # GET /petitions
  def index
    @petitions = Petition.all
    @petitions = Petition.search(params[:search]).order("created_at DESC") if params[:search]
    @petitions = @petitions.where(user: current_user) if params[:my]
  end

  # GET /petitions/1
  def show
    @petition = Petition.find(params[:id])
  end

  def edit
    @petition = current_user.petitions.find(params[:id])
  end

  # POST /petitions
  def create
    @petition = current_user.petitions.create(petition_params)
    if @petition.save
      flash[:success] = "Петиция добавлена"
      UserMailer.create_petition(@petition).deliver_later
      redirect_to petitions_path(my: true)
    else
      render new_petition_path
    end
  end

  # GET /petitions/new
  def new
    @petition = current_user.petitions.new
  end

  def search
    @search = Petition.search(params[:q])
    @petitions = @search.result(distinct: true)
  end

  def petitions
    @petitions = Petition.order(created_at: :desc).limit(10)
  end

  # PUT /petitions/1
  def update
    petition = current_user.petitions.find(params[:id])
    # if petition.expired?(petition.id)
    #   redirect_to petition, notice: 'Срок голосования петиции прошел'
    # else
    petition.update(petition_params)
    redirect_to petition, notice: 'Петиция обновлена'
    # end
  end

  def destroy
    @petition = Petition.find_by(id: params[:id])
    @petition.destroy
    flash[:success] = "Петиция удалена"
    params[:my] = true
    redirect_to petitions_path(my: true)
  end

  private

  def petition_params
    params.require(:petition).permit(:title, :text, :captcha, :captcha_key, genre_ids:[])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index

  end

  def new

  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Добро пожаловать!'
    else
      flash.now[:error] = 'Не верный пароль или email'
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Вы вышли'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    unless simple_captcha_valid?
      flash[:failure] = "Код с картинки не верный!"
      render "new" and return
    end
    if @user.save && simple_captcha_valid?
      flash[:success] = "Спасибо за регистрацию!"
      redirect_to root_url
    else
      render "new"
    end
  end

  def show
    #@user = User.find(params[:id])
    #@petitions = Petition.find(params[:id])
    #@petitions = @user.petitions.paginate(page: params[:page])
    #current_user.petitions.title
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    vote = current_user.votes.create(permitt_params)
    @petition = Petition.find(vote[:petition_id])
    redirect_to petitions_index_path, notice: 'Спасибо за поддержку!'
  end

  def permitt_params
    params.permit(:petition_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/petition_helper.rb
module PetitionHelper
  def days_last(start_time)
    end_time = start_time + Petition::ACTIVE_DAYS.days
    date_0f_p = end_time - Time.now
    dd = date_0f_p.divmod(60*60*24)
    if dd.first < 0
      'Срок истек'
    else
      dd.first
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def signed_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  # def signed_in_user
  #   unless signed_in?
  #     store_location
  #     redirect_to signin_url, notice: "Please sign in."
  #   end
  # end
end

app/views/home/index.html.erb
<h1>Последние петиции</h1>

<table align="center" width="1300">

  <tr>
    <th>Петиция</th>
    <th>Автор</th>
  </tr>
  <tr><td><%= Petition.first %></td><td>10 авторов</td></tr>

</table><p></p>

<table width="1300" align="center">
  <tr>
    <th>Петиция</th>
    <th>Автор</th>
    <th colspan="2"></th>
  </tr>

  <% @petitions.each do |petition| %>
      <tr>
        <td><%= petition.title %></td>
        <td><%= petition.text %></td>
      </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Петиции" %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Онлайн петиции нашего района</a>
    <div class="pull-right" style="margin: 10px">
          <span >
          <% if current_user %>
            <%= current_user.email %>
                (<%= link_to "Выйти", signout_path, method: "delete" %>)
          <% else %>
            <%= link_to "Зарегистироваться", signup_path %> |
                <%= link_to "Войти", login_path %>
          <% end %>
          </span>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <div class="col-lg-3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list la">
          <li><h4><%= link_to "Все петиции", petitions_path  %></h4></li>
          <li><h4><%= link_to "Создать петицию", new_petition_path  %></h4></li>
          <% if current_user %>
              <li><h4><%= link_to "Мои петиции", petitions_path(my: true)  %></h4></li>
          <% end %>
          <!--<li><h4><%= link_to "Поиск", 'petitions/search' %></h4></li>-->
        </ul>
      </div>
    </div>

  </div>
</div>
</body>
</html>

app/views/petitions/_my_index.html.erb
  <table class="table">
    <thead>
    <tr>
      <th>Петиция</th>
      <th>Голоса</th>
      <th>Дата создания</th>
      <th>Осталось дней</th>
      <th colspan="2" class="text-center">Действия</th>
    </tr>
    </thead>
    <% @petitions.each do |petition| %>
        <tr>
          <td><%= link_to petition.title, petition_path(petition) %></td>
          <td><%= petition.votes.count %></td>
          <td><%= petition.created_at.strftime("%m/%d/%Y %I:%M") %></td>
          <td><%= days_last(petition.created_at) %></td>
          <% if petition.created_at > 90.days.ago %>
          <td><%= link_to "Изменить", edit_petition_path(petition) %></td>
          <% else %>
          <td></td>
          <% end %>
          <td><%= link_to "Удалить", petition, method: :delete %> </td>
        </tr>
    <% end %>
  </table>

app/views/petitions/_petition.html.erb
<tr>
  <td><%= link_to petition.title, petition_path(petition) %></td>
  <td><%= petition.user.first_name %> <%= petition.user.last_name %></td>
  <td><%= petition.votes.count %></td>
  <td><%= petition.created_at.strftime("%m/%d/%Y %I:%M") %></td>
  <td><%= days_last(petition.created_at) %></td>
</tr>

app/views/petitions/edit.hrml.erb
<h2>Изменение петиции</h2>

<%= form_for @petition do |f| %>
    <% if @petition.errors.any? %>
        <div class="error_message">
          <h2>Form is invalid</h2>
          <ul>
            <% @petition.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group" style="width: 50%">
      <%= f.label :title, 'Название' %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 50%">
      <%= f.label :text, 'Описание' %><br />
      <%= f.text_area :text, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label "Категории" %><br />
      <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name do |b| %>
          <div class="collection-check-box">
            <%= b.check_box %>
            <%= b.label %>
          </div>
      <% end %>
    </div><br />

    <div class="action">
      <%= submit_tag 'Сохранить', class: 'btn btn-success' %>
    </div>
<% end %>

app/views/petitions/index.html.erb
<h2><%= params[:my] ? 'Мои' : 'Все' %> петиции</h2>

<% if params[:my] %>
    <%= render 'petitions/my_index' %>
<% else %>
<table class="table">
  <thead>
  <tr>
    <th>Петиция</th>
    <th>Автор</th>
    <th>Голоса</th>
    <th>Дата создания</th>
    <th>Осталось дней</th>
  </tr>
  </thead>
  <% @petitions.each do |petition| %>
      <%= render 'petition', petition: petition %>
  <% end %>
<% end %>

</table>

<%= form_tag(petitions_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Petitions" %>
    <%= submit_tag "Search" %>
<% end %>

app/views/petitions/new.html.erb
<h2>Новая петиция</h2>

<%= form_for @petition do |f| %>
    <% if @petition.errors.any? %>
        <div class="error_message">
          <h2>Form is invalid</h2>
          <ul>
            <% @petition.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group" style="width: 50%">
      <%= f.label :title, 'Название' %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 50%">
      <%= f.label :text, 'Описание' %><br />
      <%= f.text_area :text, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label "Категории" %><br />
      <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name do |b| %>
          <div class="collection-check-box">
            <%= b.check_box %>
            <%= b.label %>
          </div>
      <% end %>
    </div><br />

    <div class="action">
      <%= submit_tag 'Cоздать', class: 'btn btn-success' %>
    </div>
<% end %>

app/views/petitions/petitions.html.erb
<h2>Последние петиции</h2>
<table class="table">
  <thead>
  <tr>
    <th>Петиция</th>
    <th>Автор</th>
    <th>Голоса</th>
    <th>Дата создания</th>
    <th>Осталось дней</th>
  </tr>
  </thead>
  <% @petitions.each do |petition| %>
      <%= render 'petitions/petition', petition: petition %>
  <% end %>
</table>

app/views/petitions/search.html.erb
<fieldset class="search-field">
  <legend>Search Our Database</legend>
  <%= search_form_for @search do |f| %>
      <div class="field">
        <%= f.label :name_cont, "Name contains" %>
        <%= f.text_field :name_cont %>
      </div>

      <div class="field">
        <%= f.label "Area of Expertise" %><br />
        <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name do |b| %>
            <div class="collection-check-box">
              <%= b.check_box %>
              <%= b.label %>
            </div>
        <% end %>
      </div>

      <div class="actions"><%= f.submit "Search" %></div>
  <% end %>
</fieldset>

app/views/petitions/show.html.erb
<h1>Петиция</h1>

<div><h3><%= @petition.title %></h3></div>
<p><%= @petition.created_at.strftime("%m/%d/%Y %I:%M") %></p>
<p>
  <strong>Категории:</strong>
  <%= @petition.genres.map(&:name).sort.join(", ") %>
</p><br />
<p><h2><%= @petition.text %></h2></p>
<p>Голосов: <%= @petition.votes.count %> из <%= Petition::NEED_VOTES %></p><br />
<% if  @petition.voted_by?(current_user) %>
    Вы уже проголосовали за данную петицию
<% elsif @petition.user != current_user and !@petition.expired?(@petition.id) %>
    <%= button_to("Поддержать", votes_path(@petition, { petition_id: @petition.id }),
                  class: 'btn btn-primary btn-sm', method: :post) %><br />
<% else %>

<% end %>
<strong>Поддержавшие пользователи:</strong>
<p><% @petition.votes.each do |vote| %>
      <%= vote.user.first_name %>
      <%= vote.user.last_name %>
  <% end %>
</p>

app/views/simple_captcha/_simple_captcha.erb
<style type="text/css">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>

  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>

  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>

  <div class='simple_captcha_refresh_button'>
    <%= simple_captcha_options[:refresh_button] %>
  </div>
</div>

app/views/users/new.html.erb
<h1 xmlns="http://www.w3.org/1999/html">Регистрация</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div class="errors message">
    <h3>Данные неверные</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
 <% end %>

  <div class="form-group" style="width: 50%">
    <%= f.label :title, 'Email' %><br />
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group" style="width: 50%">
    <%= f.label :title, 'Имя' %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group" style="width: 50%">
    <%= f.label :title, 'Фамилия' %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="form-group" style="width: 50%">
    <%= f.label :title, 'Пароль' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group" style="width: 50%">
    <%= f.label :title, 'Подтверждение пароля' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

    <%= show_simple_captcha %><br />

  <div class="action"><%= submit_tag 'Зарегистрироваться', class: 'btn btn-primary'%></div>
<% end %>

app/views/users/show.html.erb
<h1>Мои петиция</h1>

<table align="left" width="900">
  <tr>
    <th>Петиция</th>
    <th>Автор</th>
    <th colspan="2"></th>
  </tr>

  <% current_user.petitions.each do |petition| %>
      <tr>
        <td><%=link_to petition.title, petition %></td>
        <td><%= petition.user.first_name%> <%= petition.user.last_name %></td>
      </tr>
  <% end %>
</table>